server:
  port: 8080
  servlet:
    context-path: /iscr

logging:
  level:
    com.qt: debug
    org.springframework: error

# MyBatis
mybatis:
  mapper-locations: classpath*:mapping/system/*Mapper.xml
  type-aliases-package: com.vsu.iscr.domain
  configuration:
    jdbc-type-for-null: 'null'


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  enabled: true
  excludes:
  urlPatterns: /system/*

# Spring配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: '@profiles.active@'
  servlet:
    multipart:
      max-file-size:  50MB
      max-request-size:  100MB
  devtools:
    restart:
      enabled: true

